-- 코드를 입력하세요
SELECT p.PRODUCT_ID AS PRODUCT_ID, p.PRODUCT_NAME AS PRODUCT_NAME, SUM(p.PRICE * o.AMOUNT) AS TOTAL_SALES FROM FOOD_ORDER o JOIN FOOD_PRODUCT p ON p.PRODUCT_ID = o.PRODUCT_ID WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') LIKE '2022-05' 
GROUP BY PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID